### ISSUE TITLE
Discord5: Sept 1

### ISSUE THREAD

**Issue by zubepaul** [smartcontractresearchforum/discovery#288]
Ticket created on engagement board
https://github.com/smartcontractresearchforum/engagement/issues/181
@MichaelSCRF

**Comment by okoba** [comment]
****Sept 2*
"Discord 5" Opportunity:**** 
Want to have a deep conversation while earning Source Cred?
Then join any of these discussions;
1. Empirical evaluations prove that Zprobe provides a low overhead solution to defend against state-of-the-art Byzantine attacks while preserving privacy. Want to learn more about the novel framework(Zprobe), click the link; https://www.smartcontractresearch.org/t/research-summary-zprobe-zero-peek-robustness-checks-for-federated-learning/1981
2. "Although unlimited approval can help users save money (gas fee) from repeatedly sending approval transactions, several security incidents in recent years suggest this mechanism has been widely abused".Engage in this deep discussion ; []https://www.smartcontractresearch.org/t/research-summary-penny-wise-and-pound-foolish-quantifying-the-risk-of-unlimited-approval-of-erc20-tokens-on-ethereum/1795l
3. "As humanity stares down increasing existential threats, some of which are already coming to fruition, the only system we rely on for impartial discovery and production is losing its credibility and functionality". join @jringo to discuss the future of trustless science: []https://www.smartcontractresearch.org/t/building-systems-of-trustless-science/1531
4. Math in solidity can be hard and challenging, dive deep into this engaging discussion to know learn how "PMBmath" is making math in solidity "fun and easy":https://www.smartcontractresearch.org/t/deep-diving-into-prbmath-a-library-for-advanced-fixed-point-math/686
5. The author identifies existing legal frameworks through which NFTs can be adjudicated as personal property instead of intellectual property. for information on this sublime summary, click the link https://www.smartcontractresearch.org/t/discussion-post-a-stable-legal-framework-for-digital-uniqueness/561

**Comment by okoba** [comment]
hi Smartcontractresearchforum/Discovery, needed to make some changes in the
text, is that still possible?

**Comment by okoba** [comment]
sept3
**"Discord 5" Opportunity:**
Want to have a deep conversation while earning Source Cred?
Then join these discussions;
1. In this paper, We examine the behaviour of rational miners that can be bribed to censor transactions for a specific period, and its effect on mechanisms that employ timelocks for safety such as payment channels. to learn more about this informative summary, click the link: []https://www.smartcontractresearch.org/t/research-summary-suborn-channels-incentives-against-timelock-bribes/2074/1
2. How are different language constructs used in practice and are they still commonly used in current smart contracts deployed in the Ethereum network? get an informative response to the question, []https://www.smartcontractresearch.org/t/research-summary-an-exploratory-study-on-solidity-guards-and-ether-exchange-constructs/2029/1)
3. Polkadot was developed to address some major shortcomings of existing blockchain technologies. However, the introduced solutions do not highlight how those limits are overcome. The paper explores several limitations found in Polkadot’s design and protocols; to engage with this summary post, []https://www.smartcontractresearch.org/t/research-summary-analysis-of-polkadot-architecture-internals-and-contradictions/1960
4. In this work, we present an analysis of such sandwich attacks for twelve months. During this time there were at least 480’276 attacks on Ethereum leading to an accumulated profit of 190 million USD. find out how sandwich attacks can be analyzed and prevented; click the link: []https://www.smartcontractresearch.org/t/research-summary-analyzing-and-preventing-sandwich-attacks-in-ethereum/1033
5. in this paper, the co-author analyzes the implications of flash loans for decentralized finance (DeFi) ecosystems and How attacker’s can maximize profit, click the link  to engage with this engaging topic ;
[]https://www.smartcontractresearch.org/t/research-summary-attacking-the-defi-ecosystem-with-flash-loans-for-fun-and-profit/260
